### PR TITLE
Remove QEMU dependency files

### PR DESCRIPTION
**Pull request by fea-wang**
To earlier build the project into an independent library, remove the QEMU dependency files and turn functions into standard ones.

### CODE REVIEW

**Review by frankchang0125 — APPROVED** [review]
LGTM, thanks~

**Comment by frankchang0125** [comment]
@fea-wang After we remove the QEMU dependencies. Does it mean we can build `libtomcrypt` as a pure external library just like other subprojects?

**Comment by fea-wang** [comment]
> @fea-wang After we remove the QEMU dependencies. Does it mean we can build `libtomcrypt` as a pure external library just like other subprojects?

@frankchang0125 Yes,  after discussing with @cwshu , he thinks that the original setting with the QEMU-header may being for speeding up the execution but it's not necessary. Without the QEMU-header, we can just make it become a pure external library.

**Comment by fea-wang** [comment]
> > @fea-wang After we remove the QEMU dependencies. Does it mean we can build `libtomcrypt` as a pure external library just like other subprojects?
> 
> @frankchang0125 Yes, after discussing with @cwshu , he thinks that the original setting with the QEMU-header may being for speeding up the execution but it's not necessary. Without the QEMU-header, we can just make it become a pure external library.

But we may need to test all os again

**Comment by cwshu** [comment]
Hi @fea-wang,
Have we already tested it (e.g. run Octane HCA test) on Linux? 
We could ask SWQA to help us test it on other OSes.

**Comment by fea-wang** [comment]
> Hi @fea-wang, Have we already tested it (e.g. run Octane HCA test) on Linux? We could ask SWQA to help us test it on other OSes.

@cwshu , yes, I have passed the hca-test on the server. I will tell Jane to help test on other OSes

**Pull request merged**
